export default [
  {
    categoryName: 'Peitoral',
    exerciseList: [
      {title: 'Supino Reto Barra', description: 'Supino Reto Halteres; Supino Reto Smith'},
      {title: 'Supino Reto Halteres', description: 'Supino Reto Barra; Supino Reto Smith'},
      {title: 'Supino Reto Smith', description: 'Supino Reto Barra; Supino Reto Halteres'},
      {title: 'Supino Inclinado Barra', description: 'Supino Inclinado Halteres; Supino Inclinado Halteres'},
      {title: 'Supino Inclinado Halteres', description: 'Supino Inclinado Barra; Supino Inclinado Smith'},
      {title: 'Supino Inclinado Smith', description: 'Supino Inclinado Barra; Supino Inclinado Halteres'},
      {title: 'Supino Declinado Barra', description: 'Supino Declinado Halteres; Supino Declinado Smith'},
      {title: 'Supino Declinado Halteres', description: 'Supino Declinado Smith; Supino Declinado Barra'},
      {title: 'Supino Declinado Smith', description: 'Supino Declinado Halteres; Supino Declinado Barra'},
      {title: 'Crucifixo Reto Halteres', description: 'Cross-Over Polia Média; Peck Deck ou Crucifixo Na Máquina'},
      {title: 'Crucifixo Inclinado Halteres', description: 'Cross-Over Polia Baixa'},
      {title: 'Crucifixo Declinado Halteres', description: 'Cross-Over Polia Alta'},
      {title: 'Cross-Over Polia Alta', description: 'Crucifixo Declinado Halteres'},
      {title: 'Cross-Over Polia Média', description: 'Crucifixo Reto Halteres; Peck Deck ou Crucifixo Na Máquina'},
      {title: 'Cross-Over Polia Baixa', description: 'Crucifixo Inclinado Halteres'},
      {title: 'Peck Deck ou Crucifixo Na Máquina', description: 'Cross-Over Polia Média; Crucifixo Reto Halteres'},
      {title: 'Flexão De Braço', description: 'Supino Reto Halteres; Supino Reto Smith; Supino Reto Barra'},
    ]
  },
  {
    categoryName: 'Dorsais',
    exerciseList: [
      {title: 'Barra Fixa Peg Pronada', description:	'Puxada Vertical Peg Pronada'},
      {title: 'Barra Fixa Peg Supinada', description:	'Puxada Vertical Peg Supinada'},
      {title: 'Barra Fixa Com Triângulo', description:	'Puxada Vertical Peg Neutra; Puxada Vertical Com Triângulo'},
      {title: 'Levantamento Terra', description:	''},
      {title: 'Puxada Vertical Peg Pronada', description:	'Barra Fixa Peg Pronada'},
      {title: 'Puxada Vertical Peg Supinada', description:	'Barra Fixa Peg Supinada'},
      {title: 'Puxada Vertical Peg Neutra', description:	'Barra Fixa Com Triângulo'},
      {title: 'Puxada Vertical Com Triângulo', description:	'Barra Fixa Com Triângulo'},
      {title: 'Remada Curvada Peg Pronada', description:	'Remada Curvada Halteres Peg Pronada; Remada Máquina Peg Pronada; Remada Cross Peg Pronada; Remada Unilateral Peg Pronada'},
      {title: 'Remada Curvada Peg Supinada', description:	'Remada Curvada Halteres Peg Supinada; Remada Máquina Peg Supinada; Remada Cross Peg Supinada; Remada Unilateral Peg Supinada'},
      {title: 'Remada Curvada Cavalinho', description:	'Remada Máquina Peg Neutra; Remada Cross Peg Neutra; Remada Unilateral Peg Neutra'},
      {title: 'Remada Curvada Halteres Peg Pronada', description:	'Remada Curvada Peg Pronada; Remada Cross Peg Pronada; Remada Unilateral Peg Pronada'},
      {title: 'Remada Curvada Halteres Peg Supinada', description:	'Remada Curvada Peg Supinada; Remada Máquina Peg Supinada; Remada Cross Peg Supinada; Remada Unilateral Peg Supinada'},
      {title: 'Remada Máquina Peg Pronada', description:	'Remada Curvada Peg Pronada; Remada Curvada Halteres Peg Pronada; Remada Cross Peg Pronada; Remada Unilateral Peg Pronada'},
      {title: 'Remada Máquina Peg Supinada', description:	'Remada Curvada Peg Supinada; Remada Curvada Halteres Peg Supinada; Remada Cross Peg Supinada; Remada Unilateral Peg Supinada'},
      {title: 'Remada Máquina Peg Neutra', description:	'Remada Curvada Cavalinho; Remada Cross Peg Neutra; Remada Unilateral Peg Neutra'},
      {title: 'Remada Cross Peg Pronada', description:	'Remada Curvada Peg Pronada; Remada Curvada Halteres Peg Pronada; Remada Máquina Peg Pronada; Remada Cross Peg Pronada; Remada Unilateral Peg Pronada'},
      {title: 'Remada Cross Peg Supinada', description:	'Remada Curvada Peg Supinada; Remada Curvada Halteres Peg Supinada; Remada Máquina Peg Supinada; Remada Unilateral Peg Supinada'},
      {title: 'Remada Cross Peg Neutra', description:	'Remada Curvada Cavalinho; Remada Máquina Peg Neutra; Remada Unilateral Peg Neutra'},
      {title: 'Remada Unilateral Peg Pronada', description:	'Remada Curvada Peg Pronada; Remada Curvada Halteres Peg Pronada; Remada Máquina Peg Pronada; Remada Cross Peg Pronada'},
      {title: 'Remada Unilateral Peg Supinada', description:	'Remada Curvada Peg Supinada; Remada Curvada Halteres Peg Supinada; Remada Máquina Peg Supinada; Remada Cross Peg Supinada'},
      {title: 'Remada Unilateral Peg Neutra', description:	'Remada Curvada Cavalinho; Remada Máquina Peg Neutra; Remada Cross Peg Neutra'},
      {title: 'Pull-Down Barra', description:	'Pull-Down Cross Peg Pronada; Pull-Down Cross Peg Supinada; Pull-Down Cross Corda'},
      {title: 'Pull-Down Cross Peg Pronada', description:	'Pull-Down Barra; Pull-Down Cross Peg Supinada; Pull-Down Cross Corda'},
      {title: 'Pull-Down Cross Peg Supinada', description:	'Pull-Down Barra; Pull-Down Cross Peg Pronada; Pull-Down Cross Corda'},
      {title: 'Pull-Down Cross Corda', description:	'Pull-Down Barra; Pull-Down Cross Peg Pronada; Pull-Down Cross Peg Supinada'},
    ]
  },
  {
    categoryName: 'Deltóides',
    exerciseList: [
      {title: 'Elevação Lateral Halteres', description: 'Elevação Lateral Sentado Halteres; Elevação Lateral Cross Posterior; Elevação Lateral Cross Anterior; Elevação Lateral Unilateral Banco Inclinado'},
      {title: 'Elevação Lateral Sentado Halteres', description: 'Elevação Lateral Halteres; Elevação Lateral Sentado Halteres; Elevação Lateral Cross Posterior; Elevação Lateral Cross Anterior; Elevação Lateral Unilateral Banco Inclinado'},
      {title: 'Elevação Lateral Cross Posterior', description: 'Elevação Lateral Halteres; Elevação Lateral Sentado Halteres; Elevação Lateral Cross Anterior; Elevação Lateral Unilateral Banco Inclinado'},
      {title: 'Elevação Lateral Cross Anterior', description: 'Elevação Lateral Halteres; Elevação Lateral Sentado Halteres; Elevação Lateral Cross Posterior; Elevação Lateral Unilateral Banco Inclinado'},
      {title: 'Elevação Lateral Unilateral Banco Inclinado', description: 'Elevação Lateral Halteres; Elevação Lateral Sentado Halteres; Elevação Lateral Cross Posterior; Elevação Lateral Cross Anterior'},
      {title: 'Elevação Frontal Barra Peg Pronada', description: 'Elevação Frontal Halteres Peg Pronada; Elevação Frontal Cross Peg Pronada'},
      {title: 'Elevação Frontal Barra Peg Supinada', description: 'Elevação Frontal Halteres Peg Supinada; Elevação Frontal Cross Peg Supinada'},
      {title: 'Elevação Frontal Halteres Peg Pronada', description: 'Elevação Frontal Barra Peg Pronada; Elevação Frontal Cross Peg Pronada'},
      {title: 'Elevação Frontal Halteres Peg Supinada', description: 'Elevação Frontal Barra Peg Supinada; Elevação Frontal Cross Peg Supinada'},
      {title: 'Elevação Frontal Halteres Peg Neutra', description: 'Elevação Frontal Cross Corda; Elevação Frontal Anilha; Elevação Frontal Cruzada'},
      {title: 'Elevação Frontal Cross Peg Pronada', description: 'Elevação Frontal Barra Peg Pronada; Elevação Frontal Halteres Peg Pronada'},
      {title: 'Elevação Frontal Cross Peg Supinada', description: 'Elevação Frontal Barra Peg Supinada; Elevação Frontal Halteres Peg Supinada'},
      {title: 'Elevação Frontal Cross Corda', description: 'Elevação Frontal Halteres Peg Neutra; Elevação Frontal Anilha; Elevação Frontal Cruzada'},
      {title: 'Elevação Frontal Anilha', description: 'Elevação Frontal Halteres Peg Neutra; Elevação Frontal Cross Corda; Elevação Frontal Cruzada'},
      {title: 'Elevação Frontal Cruzada', description: 'Elevação Frontal Halteres Peg Neutra; Elevação Frontal Cross Corda; Elevação Frontal Anilha'},
      {title: 'Crucifixo Inverso Halteres', description: 'Crucifixo Inverso Cross'},
      {title: 'Crucifixo Inverso Cross', description: 'Crucifixo Inverso Halteres'},
      {title: 'Desenvolvimento Halteres', description: 'Desenvolvimento Anterior; Desenvolvimento Posterior'},
      {title: 'Desenvolvimento Anterior', description: 'Desenvolvimento Halteres; Desenvolvimento Posterior'},
      {title: 'Desenvolvimento Posterior', description: 'Desenvolvimento Halteres; Desenvolvimento Anterior'},
      {title: 'Desenvolvimento Militar', description: 'Desenvolvimento Halteres; Desenvolvimento Anterior; Desenvolvimento Smith'},
      {title: 'Desenvolvimento Smith', description: 'Desenvolvimento Halteres; Desenvolvimento Anterior; Desenvolvimento Máquina'},
      {title: 'Desenvolvimento Máquina', description: 'Desenvolvimento Halteres; Desenvolvimento Anterior; Desenvolvimento Smith'},
      {title: 'Manguito Rotador Externo Barra', description: 'Manguito Rotador Externo Halteres'},
      {title: 'Manguito Rotador Externo Halteres', description: 'Manguito Rotador Externo Barra'},
    ]
  },
  {
    categoryName: 'Trapézio',
    exerciseList: [
      {title: 'Encolhimento Barra Anterior', description: 'Encolhimento Halteres; Encolhimento Smith Anterior'},
      {title: 'Encolhimento Barra Posterior', description: 'Encolhimento Halteres; Encolhimento Smith Posterior'},
      {title: 'Encolhimento Halteres', description: 'Encolhimento Barra Anterior; Encolhimento Barra Posterior'},
      {title: 'Encolhimento Smith Anterior', description: 'Encolhimento Barra Anterior; Encolhimento Halteres'},
      {title: 'Encolhimento Smith Posterior', description: 'Encolhimento Barra Posterior; Encolhimento Halteres'},
      {title: 'Remada Alta Halteres', description: 'Remada Alta Barra; Remada Alta Cross; Remada Alta Smith'},
      {title: 'Remada Alta Barra', description: 'Remada Alta Halteres; Remada Alta Cross; Remada Alta Smith'},
      {title: 'Remada Alta Cross', description: 'Remada Alta Halteres; Remada Alta Barra; Remada Alta Smith'},
      {title: 'Remada Alta Smith', description: 'Remada Alta Halteres; Remada Alta Barra; Remada Alta Cross'},
    ]
  },
  {
    categoryName: 'Tríceps',
    exerciseList: [
      {title: 'Paralelas', description: 'Mergulho; Supino Fechado; Flexão De Braço Fechada'},
      {title: 'Mergulho', description: 'Paralelas; Supino Fechado; Flexão De Braço Fechada'},
      {title: 'Supino Fechado', description: 'Paralelas; Mergulho; Flexão De Braço Fechada'},
      {title: 'Rosca Testa Barra Peg Pronada', description: 'Tríceps Pulley Peg Pronada; Tríceps Pulley Unilateral Peg Pronada; Rosca Francesa Barra Peg Pronada;'},
      {title: 'Rosca Testa Barra Peg Supinada', description: 'Tríceps Pulley Peg Supinada; Rosca Testa Halteres Peg Supinada; Tríceps Pulley Unilateral Peg Supinada; Rosca Francesa Barra Peg Supinada; Rosca Francesa Halteres Peg Supinada'},
      {title: 'Rosca Testa Halteres Peg Supinada', description: 'Tríceps Pulley Peg Supinada; Tríceps Pulley Unilateral Peg Supinada; Rosca Francesa Barra Peg Supinada; Rosca Francesa Halteres Peg Supinada'},
      {title: 'Rosca Testa Halteres Peg Neutra', description: 'Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda; Tríceps Coice Bilateral Halteres'},
      {title: 'Tríceps Pulley Corda', description: 'Rosca Testa Halteres Peg Neutra; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Tríceps Pulley Peg Pronada', description: 'Rosca Testa Barra Peg Pronada; Tríceps Pulley Unilateral Peg Pronada; Rosca Francesa Barra Peg Pronada'},
      {title: 'Tríceps Pulley Peg Supinada', description: 'Rosca Testa Barra Peg Supinada; Rosca Testa Halteres Peg Supinada; Tríceps Pulley Unilateral Peg Supinada; Rosca Francesa Barra Peg Supinada; Rosca Francesa Halteres Peg Supinada'},
      {title: 'Tríceps Pulley Unilateral Peg Pronada', description: 'Rosca Testa Barra Peg Pronada; Tríceps Pulley Peg Pronada; Rosca Francesa Barra Peg Pronada'},
      {title: 'Tríceps Pulley Unilateral Peg Supinada', description: 'Rosca Testa Barra Peg Supinada; Rosca Testa Halteres Peg Supinada; Tríceps Pulley Peg Supinada; Rosca Francesa Barra Peg Supinada; Rosca Francesa Halteres Peg Supinada'},
      {title: 'Rosca Francesa Anilha', description: 'Rosca Testa Halteres Peg Neutra; Tríceps Pulley Corda; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Rosca Francesa Barra Peg Pronada', description: 'Rosca Testa Barra Peg Pronada; Tríceps Pulley Peg Pronada; Tríceps Pulley Unilateral Peg Pronada;'},
      {title: 'Rosca Francesa Barra Peg Supinada', description: 'Rosca Testa Barra Peg Supinada; Rosca Testa Halteres Peg Supinada; Tríceps Pulley Peg Supinada; Rosca Francesa Halteres Peg Supinada'},
      {title: 'Rosca Francesa Halteres Peg Neutra', description: 'Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Cross Corda'},
      {title: 'Rosca Francesa Halteres Peg Supinada', description: 'Rosca Testa Barra Peg Supinada; Rosca Testa Halteres Peg Supinada; Tríceps Pulley Peg Supinada; Tríceps Pulley Unilateral Peg Supinada; Rosca Francesa Barra Peg Supinada'},
      {title: 'Rosca Francesa Cross Corda', description: 'Rosca Testa Halteres Peg Neutra; Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Tríceps Coice Bilateral Halteres', description: 'Rosca Testa Halteres Peg Neutra; Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Tríceps Coice Unilateral Halteres', description: 'Rosca Testa Halteres Peg Neutra; Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Tríceps Coice Unilateral Cross', description: 'Rosca Testa Halteres Peg Neutra; Tríceps Pulley Corda; Rosca Francesa Anilha; Rosca Francesa Halteres Peg Neutra; Rosca Francesa Cross Corda'},
      {title: 'Flexão De Braço Fechada', description: 'Mergulho; Supino Fechado; Paralelas'},
    ]
  },
  {
    categoryName: 'Bíceps',
    exerciseList: [
      {title: 'Rosca Direta Barra Reta ou Barra W', description: 'Rosca Direta Halteres; Rosca Direta Cross'},
      {title: 'Rosca Direta Halteres', description: 'Rosca Direta Barra Reta ou Barra W; Rosca Direta Cross'},
      {title: 'Rosca Direta Cross', description: 'Rosca Direta Barra Reta ou Barra W; Rosca Direta Halteres'},
      {title: 'Rosca Martelo Barra H', description: 'Rosca Martelo Halteres; Rosca Martelo Corda Cross; Rosca Concentrada Martelo'},
      {title: 'Rosca Martelo Halteres', description: 'Rosca Martelo Barra H; Rosca Martelo Corda Cross; Rosca Concentrada Martelo'},
      {title: 'Rosca Martelo Corda Cross', description: 'Rosca Martelo Barra H; Rosca Martelo Halteres; Rosca Concentrada Martelo'},
      {title: 'Rosca Alternada Halteres', description: 'Rosca Alternada Cross-Over'},
      {title: 'Rosca Alternada Cross-Over', description: 'Rosca Alternada Halteres'},
      {title: 'Rosca Scott Halteres', description: 'Rosca Scott Barra ou Barra W; Rosca Scott Máquina; Rosca Concentrada'},
      {title: 'Rosca Scott Barra ou Barra W', description: 'Rosca Scott Halteres; Rosca Scott Máquina; Rosca Concentrada'},
      {title: 'Rosca Scott Máquina', description: 'Rosca Scott Halteres; Rosca Scott Barra ou Barra W; Rosca Concentrada'},
      {title: 'Rosca Concentrada', description: 'Rosca Scott Halteres; Rosca Scott Barra ou Barra W; Rosca Scott Máquina'},
      {title: 'Rosca Concentrada Martelo', description: 'Rosca Martelo Barra H; Rosca Martelo Halteres; Rosca Martelo Corda Cross'},
    ]
  },
  {
    categoryName: 'Antebraço',
    exerciseList: [
      {title: 'Flexão de Punho Barra Sentado', description: ''},
      {title: 'Extensão de Punho Barra Sentado', description: 'Extensão de Punho Cross'},
      {title: 'Extensão de Punho Cross', description: 'Extensão de Punho Barra Sentado'},
      {title: 'Rotacional de Punho', description: ''},
      {title: 'Rosca Inversa Barra', description: 'Rosca Inversa Cross; Rosca Inversa Alternada'},
      {title: 'Rosca Inversa Cross', description: 'Rosca Inversa Barra; Rosca Inversa Alternada'},
      {title: 'Rosca Inversa Alternada', description: 'Rosca Inversa Barra; Rosca Inversa Cross'},
    ]
  },
  {
    categoryName: 'Coxas',
    exerciseList: [
      {title: 'Agachamento Livre	Agachamento Hack; Agachamento Smith; Agachamento Halteres; Leg Press'},
      {title: 'Agachamento Livre Frontal', description: 'Agachamento Smith Frontal'},
      {title: 'Agachamento Hack', description: 'Agachamento Livre; Agachamento Smith; Agachamento Halteres; Leg Press'},
      {title: 'Agachamento Smith', description: 'Agachamento Livre; Agachamento Hack; Agachamento Halteres; Leg Press'},
      {title: 'Agachamento Smith Frontal', description: 'Agachamento Livre Frontal'},
      {title: 'Agachamento Halteres', description: 'Agachamento Livre; Agachamento Hack; Agachamento Smith; Leg Press'},
      {title: 'Agachamento Adutores', description: 'Leg Press Adutores; Cadeira Adutora'},
      {title: 'Passada Barra', description: 'Passada Halteres'},
      {title: 'Passada Halteres', description: 'Passada Barra'},
      {title: 'Afundos Barra', description: 'Afundos Halteres; Afundos Smith'},
      {title: 'Afundos Halteres', description: 'Afundos Barra; Afundos Smith'},
      {title: 'Afundos Smith', description: 'Afundos Barra; Afundos Halteres'},
      {title: 'Cadeira Extensora', description: ''},
      {title: 'Mesa Flexora', description: 'Cadeira Flexora; Flexor Vertical'},
      {title: 'Cadeira Flexora', description: 'Flexor Vertical; Mesa Flexora'},
      {title: 'Flexor Vertical', description: 'Cadeira Flexora; Mesa Flexora'},
      {title: 'Leg Press', description: 'Agachamento Livre; Agachamento Hack; Agachamento Smith; Agachamento Halteres'},
      {title: 'Leg Press Adutores', description: 'Agachamento Adutores; Cadeira Adutora'},
      {title: 'Stiff Barra', description: 'Stiff Halteres; Stiff Smith'},
      {title: 'Stiff Halteres', description: 'Stiff Smith; Stiff Barra'},
      {title: 'Stiff Smith', description: 'Stiff Halteres; Stiff Barra'},
      {title: 'Agachamento Bulgaro Halteres', description: 'Agachamento Bulgaro Barra'},
      {title: 'Agachamento Bulgaro Barra', description: 'Agachamento Bulgaro Halteres'},
      {title: 'Cadeira Adutora', description: 'Agachamento Adutores; Leg Press Adutores'},
    ]
  },
  {
    categoryName: 'Glúteos',
    exerciseList: [
      {title: '4 Apoios Joelho Estendido', description: 'Glúteos Cross'},
      {title: '4 Apoios Joelho Flexionado', description: 'Glúteos Graviton; Glúteos Smith; Glúteos Máquina; Glúteos Cross'},
      {title: 'Glúteos Graviton', description: '4 Apoios Joelho Flexionado; Glúteos Máquina; Glúteos Smith'},
      {title: 'Glúteos Máquina', description: '4 Apoios Joelho Flexionado; Glúteos Graviton; Glúteos Smith'},
      {title: 'Glúteos Smith', description: '4 Apoios Joelho Flexionado; Glúteos Graviton; Glúteos Máquina'},
      {title: 'Glúteos Cross', description: '4 Apoios Joelho Estendido'},
      {title: 'Elevação Pélvica Barra', description: 'Elevação Pélvica Halter; Elevação Pélvica Anilha; Elevação Pélvica Smith'},
      {title: 'Elevação Pélvica Halter', description: 'Elevação Pélvica Barra; Elevação Pélvica Anilha; Elevação Pélvica Smith'},
      {title: 'Elevação Pélvica Anilha', description: 'Elevação Pélvica Barra; Elevação Pélvica Halter; Elevação Pélvica Smith'},
      {title: 'Elevação Pélvica Smith', description: 'Elevação Pélvica Barra; Elevação Pélvica Halter; Elevação Pélvica Anilha'},
      {title: 'Cadeira Abdutora', description: ''},
    ]
  },
  {
    categoryName: 'Panturrilhas',
    exerciseList: [
      {title: 'Gêmeos Em Pé Máquina', description: 'Gêmeos Em Pé Hack; Gêmeos Em Pé Smith; Gêmeos Em Pé Livre'},
      {title: 'Gêmeos Em Pé Hack', description: 'Gêmeos Em Pé Máquina; Gêmeos Em Pé Smith; Gêmeos Em Pé Livre'},
      {title: 'Gêmeos Em Pé Smith', description: 'Gêmeos Em Pé Máquina; Gêmeos Em Pé Hack; Gêmeos Em Pé Livre'},
      {title: 'Gêmeos Em Pé Livre', description: 'Gêmeos Em Pé Máquina; Gêmeos Em Pé Hack; Gêmeos Em Pé Smith'},
      {title: 'Gêmeos Sentado Máquina', description: 'Gêmeos Sentado Smith; Gêmeos Sentado Livre'},
      {title: 'Gêmeos Sentado Smith', description: 'Gêmeos Sentado Máquina; Gêmeos Sentado Livre'},
      {title: 'Gêmeos Sentado Livre', description: 'Gêmeos Sentado Máquina; Gêmeos Sentado Smith'},
      {title: 'Gêmeos Leg Press', description: ''},
    ]
  },
]




