export interface ExerciseVideoListProps {
  isRender: boolean, categoryName: string;
  exerciseList: { name: string; link: string;}[]
}

const ExerciseVideoList: ExerciseVideoListProps[] =  [
  {
    isRender: false, categoryName: 'Peitoral',
    exerciseList: [
      {name: 'Supino Reto Barra', link: 'sqOw2Y6uDWQ'},
      {name: 'Supino Reto Halteres', link: 'Spbmm66NsuY'},
      {name: 'Supino Reto Smith', link: 'b-THwNtIYxY'},
      {name: 'Supino Inclinado Barra', link: 'lBCjPgnIzKk'},
      {name: 'Supino Inclinado Halteres', link: 'Z1rCZ0YHrP0'},
      {name: 'Supino Inclinado Smith', link: 'L4kIk2gMeBw'},
      {name: 'Supino Declinado Barra', link: 'hZ9woVlzGdA'},
      {name: 'Supino Declinado Halteres', link: '0SFB2chQTPY'},
      {name: 'Supino Declinado Smith', link: 'xLQ9ZbH9ljc'},
      {name: 'Crucifixo Reto Halteres', link: 'dQi36EfA88c'},
      {name: 'Crucifixo Inclinado Halteres', link: '4JvT5Ys1Bog'},
      {name: 'Crucifixo Declinado Halteres', link: 'QsZ8VYaRh34'},
      {name: 'Cross-Over Polia Alta', link: 'HNUji0rHFCs'},
      {name: 'Cross-Over Polia Média', link: 'iLRFLm82dbg'},
      {name: 'Cross-Over Polia Baixa', link: 'Jy_hZnK-_lo'},
      {name: 'Flexão De Braço', link: 'F9FC_KBsLpY'},
      {name: 'Peck Deck / Crucifixo Na Máquina', link: 'Ru9OVOUlp0U'},
    ]
  },
  {
    isRender: false, categoryName: 'Dorsais',
    exerciseList: [
      {name: 'Barra Fixa Peg Pronada', link: 'JX_YM7Bp26U'},
      {name: 'Barra Fixa Peg Supinada', link: 'WJOu_aru3XM'},
      {name: 'Barra Fixa Com Triângulo', link: 'uCnmHgHgfOs'},
      {name: 'Levantamento Terra', link: 'T3x53s0jEns'},
      {name: 'Puxada Vertical Peg Pronada', link: 'H09EvebBsB4'},
      {name: 'Puxada Vertical Peg Supinada', link: 'v1rPzvJvwIE'},
      {name: 'Puxada Vertical Com Triângulo', link: 'ej9Z_jMQpLY'},
      {name: 'Remada Curvada Peg Pronada', link: 'XruycmUNi1Y'},
      {name: 'Remada Curvada Peg Supinada', link: 'y-XZnuKx3Q0'},
      {name: 'Remada Curvada Cavalinho', link: 'Hdqf7mlEHrA'},
      {name: 'Remada Curvada Halteres Peg Pronada', link: 'AT8pPML17VU'},
      {name: 'Remada Curvada Halteres Peg Supinada', link: 'g0VduhIsJIE'},
      {name: 'Remada Curvada Halteres Peg Neutra', link: 'CyCkDYs49hM'},
      {name: 'Remada Máquina Peg Pronada', link: '_g6GeyWVivI'},
      {name: 'Remada Máquina Peg Supinada', link: '1CG-dreRL6Q'},
      {name: 'Remada Máquina Peg Neutra', link: 'C0-C0X7G8eQ'},
      {name: 'Remada Cross Peg Pronada', link: 'IA0SRm2mY9M'},
      {name: 'Remada Cross Peg Supinada', link: 'Q5Rl_fnOCBs'},
      {name: 'Remada Cross Peg Neutra', link: 'wC1EsDy_esM'},
      {name: 'Remada Unilateral Peg Pronada', link: 'VlCc-rDbwhA'},
      {name: 'Remada Unilateral Peg Supinada', link: 'MAHNlcA4oXc'},
      {name: 'Remada Unilateral Peg Neutra', link: 'C-tlPEhjwTk'},
      {name: 'Pull-Down Barra', link: 'qw37xEEcoig'},
      {name: 'Pull-Down Cross Peg Pronada', link: 'EG1ua8lDQJA'},
      {name: 'Pull-Down Cross Peg Supinada', link: 'U80znmkD2z0'},
      {name: 'Pull-Down Cross Corda', link: 'zdLHXB9Sn88'},
    ]
  },
  {
    isRender: false, categoryName: 'Deltóides',
    exerciseList: [
      {name: 'Elevação Lateral Halteres', link: '89K5H0Vvhnw'},
      {name: 'Elevação Lateral Sentado Halteres', link: 'esWhjFJMNtU'},
      {name: 'Elevação Lateral Cross Posterior', link: 'I-ywK8Q-9TM'},
      {name: 'Elevação Lateral Cross Anterior', link: '8KOat8ZsidI'},
      {name: 'Elevação Lateral Unilateral Banco Inclinado', link: '8s9JRhE95mU'},
      {name: 'Elevação Frontal Barra Peg Pronada', link: 'jXUIrrvlR_0'},
      {name: 'Elevação Frontal Barra Peg Supinada', link: 'Ea_8qpcysYI'},
      {name: 'Elevação Frontal Halteres Peg Pronada', link: '0K9NJHXYSm4'},
      {name: 'Elevação Frontal Halteres Peg Supinada', link: 'DuUh84gcaso'},
      {name: 'Elevação Frontal Halteres Peg Neutra', link: 'kQTNDsaEIKc'},
      {name: 'Elevação Frontal Cross Peg Pronada', link: 'mOTjgenwgUc'},
      {name: 'Elevação Frontal Cross Peg Supinada', link: 'lL8hIRuFcnU'},
      {name: 'Elevação Frontal Cross Corda', link: 'xCQLo6LcudM'},
      {name: 'Elevação Frontal Anilha', link: '5bdlcZZvpzE'},
      {name: 'Elevação Frontal Cruzada', link: 'btAEYSe5kp0'},
      {name: 'Crucifixo Inverso Halteres', link: 'SLQZOByDo04'},
      {name: 'Crucifixo Inverso Cross', link: 'gWa5abtK4G4'},
      {name: 'Desenvolvimento Halteres', link: '4pU-kV-OaVU'},
      {name: 'Desenvolvimento Anterior', link: 'V_15VvJ3mr4'},
      {name: 'Desenvolvimento Posterior', link: 'WIlm9oHEEq8'},
      {name: 'Desenvolvimento Militar', link: 'urj7vgvfojk'},
      {name: 'Desenvolvimento Smith', link: 'oi18jaIbFRM'},
      {name: 'Desenvolvimento Máquina', link: 'oBF4YIwh_w8'},
      {name: 'Manguito Rotador Externo Barra', link: 'QdUn8TBdjvU'},
      {name: 'Manguito Rotador Externo Halteres', link: '2ecstA3a5f4'},
    ]
  },
  {
    isRender: false, categoryName: 'Trapézio',
    exerciseList: [
      {name: 'Encolhimento Barra Anterior', link: 'FutT8_yYJ58'},
      {name: 'Encolhimento Barra Posterior', link: 'Y4w7ZZW84eM'},
      {name: 'Encolhimento Halteres', link: 'ZzJ3zelC0qI'},
      {name: 'Encolhimento Smith Anterior', link: '5DQl_71T8iI'},
      {name: 'Encolhimento Smith Posterior', link: '7Ui8zi1w5A4'},
      {name: 'Remada Alta Halteres', link: 'hFMCum41W9c'},
      {name: 'Remada Alta Barra', link: 'Z6jSLKXZ0Ag'},
      {name: 'Remada Alta Cross', link: 'dHjEyNaCmn0'},
      {name: 'Remada Alta Smith', link: 'lD_zvmzP1K0'},
    ]
  },
  {
    isRender: false, categoryName: 'Tríceps',
    exerciseList: [
      {name: 'Paralelas', link: '8ZhWzT-V54Q'},
      {name: 'Mergulho', link: 'jAkRzFnEvSo'},
      {name: 'Supino Fechado', link: 'qJGw6CnVh2Q'},
      {name: 'Rosca Testa Barra Peg Pronada', link: 'orMEOzQjiAs'},
      {name: 'Rosca Testa Barra Peg Supinada', link: 'D_wnqWbIrYs'},
      {name: 'Rosca Testa Halteres Peg Supinada', link: 'OS8sz24YV1g'},
      {name: 'Rosca Testa Halteres Peg Neutra', link: 'KzKdkwIjZg8'},
      {name: 'Rosca Testa Halteres Peg Pronada', link: 'esAavWMIRZ8'},
      {name: 'Tríceps Pulley Corda', link: '_KrR8248eLo'},
      {name: 'Tríceps Pulley Peg Pronada', link: 'QDt8P44ORa4'},
      {name: 'Tríceps Pulley Peg Supinada', link: '2W09NaNpiOA'},
      {name: 'Tríceps Pulley Unilateral Peg Pronada', link: 'TmO_85EK09I'},
      {name: 'Tríceps Pulley Unilateral Peg Supinada', link: 'iO5EOd9Xe4c'},
      {name: 'Rosca Francesa Anilha', link: 'D2oQJTz-RCA'},
      {name: 'Rosca Francesa Barra Peg Pronada', link: 'fcIzvqXOJzs'},
      {name: 'Rosca Francesa Barra Peg Supinada', link: 'xnP-A7ig8No'},
      {name: 'Rosca Francesa Halteres Peg Neutra', link: 'aI8x4pHiByU'},
      {name: 'Rosca Francesa Halteres Peg Supinada', link: 'KoLqZRyZuuU'},
      {name: 'Rosca Francesa Halteres Peg Pronada', link: 'DCbDClEDQvQ'},
      {name: 'Rosca Francesa Cross Corda', link: 'QhJ67UyNdsc'},
      {name: 'Tríceps Coice Bilateral Halteres', link: 'lbYQgZvJApA'},
      {name: 'Tríceps Coice Unilateral Halteres', link: 'I4hzS9nYlgs'},
      {name: 'Tríceps Coice Unilateral Cross', link: 'MGlqvfSCWLQ'},
      {name: 'Flexão De Braço Fechada', link: '9qT4QxmIuuU'},
    ]
  },
  {
    isRender: false, categoryName: 'Bíceps',
    exerciseList: [
      {name: 'Rosca Direta Barra Reta ou Barra W', link: 'po8ibB0yY0Q'},
      {name: 'Rosca Direta Halteres', link: 'ilyxkSNoyL8'},
      {name: 'Rosca Direta Cross', link: '_t2nQjiyboo'},
      {name: 'Rosca Martelo Barra H', link: '4YbWsz77mfc'},
      {name: 'Rosca Martelo Halteres', link: 'KnymofpyiIQ'},
      {name: 'Rosca Martelo Corda Cross', link: 'TXYeSl2QT50'},
      {name: 'Rosca Alternada Halteres', link: 'v15BcmivG8g'},
      {name: 'Rosca Alternada Cross-Over', link: 'LiiNiYF4lPY'},
      {name: 'Rosca Scott Halteres', link: 'WbHASg1d29w'},
      {name: 'Rosca Scott Barra ou Barra W', link: 'wQRRqKu9g7U'},
      {name: 'Rosca Scott Máquina', link: '3GfAZv126D0'},
      {name: 'Rosca Concentrada', link: 'Cryg5VkGQBw'},
      {name: 'Rosca Concentrada Martelo', link: 'ysjKbVT6-FQ'},
    ]
  },
  {
    isRender: false, categoryName: 'Antebraço',
    exerciseList: [
      {name: 'Flexão de Punho Barra Sentado', link: 'pfNPsnjVWb4'},
      {name: 'Flexão de Punho Barra Em Pé', link: 'PF1w-a7yQus'},
      {name: 'Extensão de Punho Barra Sentado', link: 'gHY5opbOhNE'},
      {name: 'Extensão de Punho Barra Em Pé', link: 'guTTkQcy8jU'},
      {name: 'Extensão de Punho Cross', link: 'SYHfATlt7LI'},
      {name: 'Flexão de Punho Cross', link: '4_Zf2r-2rAo'},
      {name: 'Rotacional de Punho', link: 'MZ8y2hqjHxQ'},
      {name: 'Rosca Inversa Barra', link: 'G1L3eV-a7gg'},
      {name: 'Rosca Inversa Cross', link: '0587NfWzEec'},
      {name: 'Rosca Inversa Alternada', link: 'k86sqzLgiwY'},
    ]
  },
  {
    isRender: false, categoryName: 'Coxas',
    exerciseList: [
      {name: 'Agachamento Livre', link: '4TG8JdU6NPU'},
      {name: 'Agachamento Livre Frontal', link: 'fJtI1_eUb2g'},
      {name: 'Agachamento Hack', link: 'QZglgfUQZdk'},
      {name: 'Agachamento Smith', link: '4vA727LveHQ'},
      {name: 'Agachamento Smith Frontal', link: '_lPh4iHfvXA'},
      {name: 'Agachamento Halteres', link: 'CROT8O8X_u0'},
      {name: 'Agachamento Adutores', link: 'T64bNYs5-gI'},
      {name: 'Passada Barra', link: 'q8oWAsKvdT0'},
      {name: 'Passada Halteres', link: 'PCSEZejLkjk'},
      {name: 'Afundos Barra', link: 'YoQL-sR3kFo'},
      {name: 'Afundos Halteres', link: 'vj7uUw_5HYY'},
      {name: 'Afundos Smith', link: '0YjOOxFc7fY'},
      {name: 'Cadeira Extensora', link: '1f1DjMr68hY'},
      {name: 'Mesa Flexora', link: 'OMKhQ2O11fc'},
      {name: 'Cadeira Flexora', link: 'n8j1X_xByD4'},
      {name: 'Flexor Vertical', link: 'HGoN-nfJFGE'},
      {name: 'Leg Press', link: 'kyESFAj3W0E'},
      {name: 'Leg Press Adutores', link: '1kjxuWNPBUc'},
      {name: 'Stiff Barra', link: 'Xgql23RkpBk'},
      {name: 'Stiff Halteres', link: 'mNsSgOKopbE'},
      {name: 'Stiff Smith', link: 'QDLNogcXvHU'},
      {name: 'Agachamento Bulgaro Halteres', link: 'WyMsCylTcKM'},
      {name: 'Agachamento Bulgaro Barra', link: 'wENBoTTRDa8'},
      {name: 'Cadeira Adutora', link: 'UB5qna8tQkw'},
    ]
  },
  {
    isRender: false, categoryName: 'Glúteos',
    exerciseList: [
      {name: '4 Apoios Joelho Estendido', link: 'C1LK-ca840k'},
      {name: '4 Apoios Joelho Flexionado', link: '3H_WSx0dK-I'},
      {name: 'Glúteos Graviton', link: 'F2yGtpW4J4s'},
      {name: 'Glúteos Máquina', link: 'A68gT5W_J50'},
      {name: 'Glúteos Smith', link: 'PMbVxKqNM7I'},
      {name: 'Glúteos Cross', link: 'vgjt9LUm6Jg'},
      {name: 'Elevação Pélvica Barra', link: 'jqgDVIv581k'},
      {name: 'Elevação Pélvica Halter', link: 'XNbfCoWFcFs'},
      {name: 'Elevação Pélvica Anilha', link: '0lPFQdMtNBU'},
      {name: 'Elevação Pélvica Smith', link: '0I3xQYtPCGQ'},
      {name: 'Cadeira Abdutora', link: 'yVZ0Vs7j6EM'},
    ]
  },
  {
    isRender: false, categoryName: 'Panturrilhas',
    exerciseList: [
      {name: 'Gêmeos Em Pé Máquina', link: 'hlQbAQB61_Y'},
      {name: 'Gêmeos Em Pé Hack', link: 'GAn7R1U3EDw'},
      {name: 'Gêmeos Em Pé Smith', link: 'ER72bXEam4c'},
      {name: 'Gêmeos Em Pé Livre', link: 'VMa37XJdejk'},
      {name: 'Gêmeos Sentado Máquina', link: 'gBIxBWBorB8'},
      {name: 'Gêmeos Sentado Smith', link: 'iK6cVWR3-jI'},
      {name: 'Gêmeos Sentado Livre', link: 'CiFlAqIx-lY'},
      {name: 'Gêmeos Leg Press', link: 'omdVB4rQnoQ'},
    ]
  },
  {
    isRender: false, categoryName: 'Abdômen / Core / Lombar',
    exerciseList: [
      {name: 'Supra', link: 'N5SL7rhM07c'},
      {name: 'Infra', link: '8slFJ9J31lM'},
      {name: 'Oblíquos', link: 'k9rfQiXoM1w'},
      {name: 'Prancha', link: 'TxadpmTHK08'},
      {name: 'Extensão Lombar', link: 'Jto980puQ3c'},
    ]
  }
];

export default ExerciseVideoList;
