export interface ExerciseVideoListProps {
  isRender: boolean, categoryName: string;
  exerciseList: { name: string; link: string;}[]
}

const ExerciseVideoList: ExerciseVideoListProps[] =  [
  {
    isRender: false, categoryName: 'Peitoral',
    exerciseList: [
      {name: 'Supino Reto Barra', link: 'https://www.youtube.com/embed/sqOw2Y6uDWQ'},
      {name: 'Supino Reto Halteres', link: 'https://www.youtube.com/embed/Spbmm66NsuY'},
      {name: 'Supino Reto Smith', link: 'https://www.youtube.com/embed/b-THwNtIYxY'},
      {name: 'Supino Inclinado Barra', link: 'https://www.youtube.com/embed/lBCjPgnIzKk'},
      {name: 'Supino Inclinado Halteres', link: 'https://www.youtube.com/embed/Z1rCZ0YHrP0'},
      {name: 'Supino Inclinado Smith', link: 'https://www.youtube.com/embed/L4kIk2gMeBw'},
      {name: 'Supino Declinado Barra', link: 'https://www.youtube.com/embed/hZ9woVlzGdA'},
      {name: 'Supino Declinado Halteres', link: 'https://www.youtube.com/embed/0SFB2chQTPY'},
      {name: 'Supino Declinado Smith', link: 'https://www.youtube.com/embed/xLQ9ZbH9ljc'},
      {name: 'Crucifixo Reto Halteres', link: 'https://www.youtube.com/embed/dQi36EfA88c'},
      {name: 'Crucifixo Inclinado Halteres', link: 'https://www.youtube.com/embed/4JvT5Ys1Bog'},
      {name: 'Crucifixo Declinado Halteres', link: 'https://www.youtube.com/embed/QsZ8VYaRh34'},
      {name: 'Cross-Over Polia Alta', link: 'https://www.youtube.com/embed/HNUji0rHFCs'},
      {name: 'Cross-Over Polia Média', link: 'https://www.youtube.com/embed/iLRFLm82dbg'},
      {name: 'Cross-Over Polia Baixa', link: 'https://www.youtube.com/embed/Jy_hZnK-_lo'},
      {name: 'Flexão De Braço', link: 'https://www.youtube.com/embed/F9FC_KBsLpY'},
      {name: 'Peck Deck / Crucifixo Na Máquina', link: 'https://www.youtube.com/embed/Ru9OVOUlp0U'},
    ]
  },
  {
    isRender: false, categoryName: 'Dorsais',
    exerciseList: [
      {name: 'Barra Fixa Peg Pronada', link: 'https://www.youtube.com/embed/JX_YM7Bp26U'},
      {name: 'Barra Fixa Peg Supinada', link: 'https://www.youtube.com/embed/WJOu_aru3XM'},
      {name: 'Barra Fixa Com Triângulo', link: 'https://www.youtube.com/embed/uCnmHgHgfOs'},
      {name: 'Levantamento Terra', link: 'https://www.youtube.com/embed/T3x53s0jEns'},
      {name: 'Puxada Vertical Peg Pronada', link: 'https://www.youtube.com/embed/H09EvebBsB4'},
      {name: 'Puxada Vertical Peg Supinada', link: 'https://www.youtube.com/embed/v1rPzvJvwIE'},
      {name: 'Puxada Vertical Com Triângulo', link: 'https://www.youtube.com/embed/ej9Z_jMQpLY'},
      {name: 'Remada Curvada Peg Pronada', link: 'https://www.youtube.com/embed/XruycmUNi1Y'},
      {name: 'Remada Curvada Peg Supinada', link: 'https://www.youtube.com/embed/y-XZnuKx3Q0'},
      {name: 'Remada Curvada Cavalinho', link: 'https://www.youtube.com/embed/Hdqf7mlEHrA'},
      {name: 'Remada Curvada Halteres Peg Pronada', link: 'https://www.youtube.com/embed/AT8pPML17VU'},
      {name: 'Remada Curvada Halteres Peg Supinada', link: 'https://www.youtube.com/embed/g0VduhIsJIE'},
      {name: 'Remada Curvada Halteres Peg Neutra', link: 'https://www.youtube.com/embed/CyCkDYs49hM'},
      {name: 'Remada Máquina Peg Pronada', link: 'https://www.youtube.com/embed/_g6GeyWVivI'},
      {name: 'Remada Máquina Peg Supinada', link: 'https://www.youtube.com/embed/1CG-dreRL6Q'},
      {name: 'Remada Máquina Peg Neutra', link: 'https://www.youtube.com/embed/C0-C0X7G8eQ'},
      {name: 'Remada Cross Peg Pronada', link: 'https://www.youtube.com/embed/IA0SRm2mY9M'},
      {name: 'Remada Cross Peg Supinada', link: 'https://www.youtube.com/embed/Q5Rl_fnOCBs'},
      {name: 'Remada Cross Peg Neutra', link: 'https://www.youtube.com/embed/wC1EsDy_esM'},
      {name: 'Remada Unilateral Peg Pronada', link: 'https://www.youtube.com/embed/VlCc-rDbwhA'},
      {name: 'Remada Unilateral Peg Supinada', link: 'https://www.youtube.com/embed/MAHNlcA4oXc'},
      {name: 'Remada Unilateral Peg Neutra', link: 'https://www.youtube.com/embed/C-tlPEhjwTk'},
      {name: 'Pull-Down Barra', link: 'https://www.youtube.com/embed/qw37xEEcoig'},
      {name: 'Pull-Down Cross Peg Pronada', link: 'https://www.youtube.com/embed/EG1ua8lDQJA'},
      {name: 'Pull-Down Cross Peg Supinada', link: 'https://www.youtube.com/embed/U80znmkD2z0'},
      {name: 'Pull-Down Cross Corda', link: 'https://www.youtube.com/embed/zdLHXB9Sn88'},
    ]
  },
  {
    isRender: false, categoryName: 'Deltóides',
    exerciseList: [
      {name: 'Elevação Lateral Halteres', link: 'https://www.youtube.com/embed/89K5H0Vvhnw'},
      {name: 'Elevação Lateral Sentado Halteres', link: 'https://www.youtube.com/embed/esWhjFJMNtU'},
      {name: 'Elevação Lateral Cross Posterior', link: 'https://www.youtube.com/embed/I-ywK8Q-9TM'},
      {name: 'Elevação Lateral Cross Anterior', link: 'https://www.youtube.com/embed/8KOat8ZsidI'},
      {name: 'Elevação Lateral Unilateral Banco Inclinado', link: 'https://www.youtube.com/embed/8s9JRhE95mU'},
      {name: 'Elevação Frontal Barra Peg Pronada', link: 'https://www.youtube.com/embed/jXUIrrvlR_0'},
      {name: 'Elevação Frontal Barra Peg Supinada', link: 'https://www.youtube.com/embed/Ea_8qpcysYI'},
      {name: 'Elevação Frontal Halteres Peg Pronada', link: 'https://www.youtube.com/embed/0K9NJHXYSm4'},
      {name: 'Elevação Frontal Halteres Peg Supinada', link: 'https://www.youtube.com/embed/DuUh84gcaso'},
      {name: 'Elevação Frontal Halteres Peg Neutra', link: 'https://www.youtube.com/embed/kQTNDsaEIKc'},
      {name: 'Elevação Frontal Cross Peg Pronada', link: 'https://www.youtube.com/embed/mOTjgenwgUc'},
      {name: 'Elevação Frontal Cross Peg Supinada', link: 'https://www.youtube.com/embed/lL8hIRuFcnU'},
      {name: 'Elevação Frontal Cross Corda', link: 'https://www.youtube.com/embed/xCQLo6LcudM'},
      {name: 'Elevação Frontal Anilha', link: 'https://www.youtube.com/embed/5bdlcZZvpzE'},
      {name: 'Elevação Frontal Cruzada', link: 'https://www.youtube.com/embed/btAEYSe5kp0'},
      {name: 'Crucifixo Inverso Halteres', link: 'https://www.youtube.com/embed/SLQZOByDo04'},
      {name: 'Crucifixo Inverso Cross', link: 'https://www.youtube.com/embed/gWa5abtK4G4'},
      {name: 'Desenvolvimento Halteres', link: 'https://www.youtube.com/embed/4pU-kV-OaVU'},
      {name: 'Desenvolvimento Anterior', link: 'https://www.youtube.com/embed/V_15VvJ3mr4'},
      {name: 'Desenvolvimento Posterior', link: 'https://www.youtube.com/embed/WIlm9oHEEq8'},
      {name: 'Desenvolvimento Militar', link: 'https://www.youtube.com/embed/urj7vgvfojk'},
      {name: 'Desenvolvimento Smith', link: 'https://www.youtube.com/embed/oi18jaIbFRM'},
      {name: 'Desenvolvimento Máquina', link: 'https://www.youtube.com/embed/oBF4YIwh_w8'},
      {name: 'Manguito Rotador Externo Barra', link: 'https://www.youtube.com/embed/QdUn8TBdjvU'},
      {name: 'Manguito Rotador Externo Halteres', link: 'https://www.youtube.com/embed/2ecstA3a5f4'},
    ]
  },
  {
    isRender: false, categoryName: 'Trapézio',
    exerciseList: [
      {name: 'Encolhimento Barra Anterior', link: 'https://www.youtube.com/embed/FutT8_yYJ58'},
      {name: 'Encolhimento Barra Posterior', link: 'https://www.youtube.com/embed/Y4w7ZZW84eM'},
      {name: 'Encolhimento Halteres', link: 'https://www.youtube.com/embed/ZzJ3zelC0qI'},
      {name: 'Encolhimento Smith Anterior', link: 'https://www.youtube.com/embed/5DQl_71T8iI'},
      {name: 'Encolhimento Smith Posterior', link: 'https://www.youtube.com/embed/7Ui8zi1w5A4'},
      {name: 'Remada Alta Halteres', link: 'https://www.youtube.com/embed/hFMCum41W9c'},
      {name: 'Remada Alta Barra', link: 'https://www.youtube.com/embed/Z6jSLKXZ0Ag'},
      {name: 'Remada Alta Cross', link: 'https://www.youtube.com/embed/dHjEyNaCmn0'},
      {name: 'Remada Alta Smith', link: 'https://www.youtube.com/embed/lD_zvmzP1K0'},
    ]
  },
  {
    isRender: false, categoryName: 'Tríceps',
    exerciseList: [
      {name: 'Paralelas', link: 'https://www.youtube.com/embed/8ZhWzT-V54Q'},
      {name: 'Mergulho', link: 'https://www.youtube.com/embed/jAkRzFnEvSo'},
      {name: 'Supino Fechado', link: 'https://www.youtube.com/embed/qJGw6CnVh2Q'},
      {name: 'Rosca Testa Barra Peg Pronada', link: 'https://www.youtube.com/embed/orMEOzQjiAs'},
      {name: 'Rosca Testa Barra Peg Supinada', link: 'https://www.youtube.com/embed/D_wnqWbIrYs'},
      {name: 'Rosca Testa Halteres Peg Supinada', link: 'https://www.youtube.com/embed/OS8sz24YV1g'},
      {name: 'Rosca Testa Halteres Peg Neutra', link: 'https://www.youtube.com/embed/KzKdkwIjZg8'},
      {name: 'Rosca Testa Halteres Peg Pronada', link: 'https://www.youtube.com/embed/esAavWMIRZ8'},
      {name: 'Tríceps Pulley Corda', link: 'https://www.youtube.com/embed/_KrR8248eLo'},
      {name: 'Tríceps Pulley Peg Pronada', link: 'https://www.youtube.com/embed/QDt8P44ORa4'},
      {name: 'Tríceps Pulley Peg Supinada', link: 'https://www.youtube.com/embed/2W09NaNpiOA'},
      {name: 'Tríceps Pulley Unilateral Peg Pronada', link: 'https://www.youtube.com/embed/TmO_85EK09I'},
      {name: 'Tríceps Pulley Unilateral Peg Supinada', link: 'https://www.youtube.com/embed/iO5EOd9Xe4c'},
      {name: 'Rosca Francesa Anilha', link: 'https://www.youtube.com/embed/D2oQJTz-RCA'},
      {name: 'Rosca Francesa Barra Peg Pronada', link: 'https://www.youtube.com/embed/fcIzvqXOJzs'},
      {name: 'Rosca Francesa Barra Peg Supinada', link: 'https://www.youtube.com/embed/xnP-A7ig8No'},
      {name: 'Rosca Francesa Halteres Peg Neutra', link: 'https://www.youtube.com/embed/aI8x4pHiByU'},
      {name: 'Rosca Francesa Halteres Peg Supinada', link: 'https://www.youtube.com/embed/KoLqZRyZuuU'},
      {name: 'Rosca Francesa Halteres Peg Pronada', link: 'https://www.youtube.com/embed/DCbDClEDQvQ'},
      {name: 'Rosca Francesa Cross Corda', link: 'https://www.youtube.com/embed/QhJ67UyNdsc'},
      {name: 'Tríceps Coice Bilateral Halteres', link: 'https://www.youtube.com/embed/lbYQgZvJApA'},
      {name: 'Tríceps Coice Unilateral Halteres', link: 'https://www.youtube.com/embed/I4hzS9nYlgs'},
      {name: 'Tríceps Coice Unilateral Cross', link: 'https://www.youtube.com/embed/MGlqvfSCWLQ'},
      {name: 'Flexão De Braço Fechada', link: 'https://www.youtube.com/embed/9qT4QxmIuuU'},
    ]
  },
  {
    isRender: false, categoryName: 'Bíceps',
    exerciseList: [
      {name: 'Rosca Direta Barra Reta ou Barra W', link: 'https://www.youtube.com/embed/po8ibB0yY0Q'},
      {name: 'Rosca Direta Halteres', link: 'https://www.youtube.com/embed/ilyxkSNoyL8'},
      {name: 'Rosca Direta Cross', link: 'https://www.youtube.com/embed/_t2nQjiyboo'},
      {name: 'Rosca Martelo Barra H', link: 'https://www.youtube.com/embed/4YbWsz77mfc'},
      {name: 'Rosca Martelo Halteres', link: 'https://www.youtube.com/embed/KnymofpyiIQ'},
      {name: 'Rosca Martelo Corda Cross', link: 'https://www.youtube.com/embed/TXYeSl2QT50'},
      {name: 'Rosca Alternada Halteres', link: 'https://www.youtube.com/embed/v15BcmivG8g'},
      {name: 'Rosca Alternada Cross-Over', link: 'https://www.youtube.com/embed/LiiNiYF4lPY'},
      {name: 'Rosca Scott Halteres', link: 'https://www.youtube.com/embed/WbHASg1d29w'},
      {name: 'Rosca Scott Barra ou Barra W', link: 'https://www.youtube.com/embed/wQRRqKu9g7U'},
      {name: 'Rosca Scott Máquina', link: 'https://www.youtube.com/embed/3GfAZv126D0'},
      {name: 'Rosca Concentrada', link: 'https://www.youtube.com/embed/Cryg5VkGQBw'},
      {name: 'Rosca Concentrada Martelo', link: 'https://www.youtube.com/embed/ysjKbVT6-FQ'},
    ]
  },
  {
    isRender: false, categoryName: 'Antebraço',
    exerciseList: [
      {name: 'Flexão de Punho Barra Sentado', link: 'https://www.youtube.com/embed/pfNPsnjVWb4'},
      {name: 'Flexão de Punho Barra Em Pé', link: 'https://www.youtube.com/embed/PF1w-a7yQus'},
      {name: 'Extensão de Punho Barra Sentado', link: 'https://www.youtube.com/embed/gHY5opbOhNE'},
      {name: 'Extensão de Punho Barra Em Pé', link: 'https://www.youtube.com/embed/guTTkQcy8jU'},
      {name: 'Extensão de Punho Cross', link: 'https://www.youtube.com/embed/SYHfATlt7LI'},
      {name: 'Flexão de Punho Cross', link: 'https://www.youtube.com/embed/4_Zf2r-2rAo'},
      {name: 'Rotacional de Punho', link: 'https://www.youtube.com/embed/MZ8y2hqjHxQ'},
      {name: 'Rosca Inversa Barra', link: 'https://www.youtube.com/embed/G1L3eV-a7gg'},
      {name: 'Rosca Inversa Cross', link: 'https://www.youtube.com/embed/0587NfWzEec'},
      {name: 'Rosca Inversa Alternada', link: 'https://www.youtube.com/embed/k86sqzLgiwY'},
    ]
  },
  {
    isRender: false, categoryName: 'Coxas',
    exerciseList: [
      {name: 'Agachamento Livre', link: 'https://www.youtube.com/embed/4TG8JdU6NPU'},
      {name: 'Agachamento Livre Frontal', link: 'https://www.youtube.com/embed/fJtI1_eUb2g'},
      {name: 'Agachamento Hack', link: 'https://www.youtube.com/embed/QZglgfUQZdk'},
      {name: 'Agachamento Smith', link: 'https://www.youtube.com/embed/4vA727LveHQ'},
      {name: 'Agachamento Smith Frontal', link: 'https://www.youtube.com/embed/_lPh4iHfvXA'},
      {name: 'Agachamento Halteres', link: 'https://www.youtube.com/embed/CROT8O8X_u0'},
      {name: 'Agachamento Adutores', link: 'https://www.youtube.com/embed/T64bNYs5-gI'},
      {name: 'Passada Barra', link: 'https://www.youtube.com/embed/q8oWAsKvdT0'},
      {name: 'Passada Halteres', link: 'https://www.youtube.com/embed/PCSEZejLkjk'},
      {name: 'Afundos Barra', link: 'https://www.youtube.com/embed/YoQL-sR3kFo'},
      {name: 'Afundos Halteres', link: 'https://www.youtube.com/embed/vj7uUw_5HYY'},
      {name: 'Afundos Smith', link: 'https://www.youtube.com/embed/0YjOOxFc7fY'},
      {name: 'Cadeira Extensora', link: 'https://www.youtube.com/embed/1f1DjMr68hY'},
      {name: 'Mesa Flexora', link: 'https://www.youtube.com/embed/OMKhQ2O11fc'},
      {name: 'Cadeira Flexora', link: 'https://www.youtube.com/embed/n8j1X_xByD4'},
      {name: 'Flexor Vertical', link: 'https://www.youtube.com/embed/HGoN-nfJFGE'},
      {name: 'Leg Press', link: 'https://www.youtube.com/embed/kyESFAj3W0E'},
      {name: 'Leg Press Adutores', link: 'https://www.youtube.com/embed/1kjxuWNPBUc'},
      {name: 'Stiff Barra', link: 'https://www.youtube.com/embed/Xgql23RkpBk'},
      {name: 'Stiff Halteres', link: 'https://www.youtube.com/embed/mNsSgOKopbE'},
      {name: 'Stiff Smith', link: 'https://www.youtube.com/embed/QDLNogcXvHU'},
      {name: 'Agachamento Bulgaro Halteres', link: 'https://www.youtube.com/embed/WyMsCylTcKM'},
      {name: 'Agachamento Bulgaro Barra', link: 'https://www.youtube.com/embed/wENBoTTRDa8'},
      {name: 'Cadeira Adutora', link: 'https://www.youtube.com/embed/UB5qna8tQkw'},
    ]
  },
  {
    isRender: false, categoryName: 'Glúteos',
    exerciseList: [
      {name: '4 Apoios Joelho Estendido', link: 'https://www.youtube.com/embed/C1LK-ca840k'},
      {name: '4 Apoios Joelho Flexionado', link: 'https://www.youtube.com/embed/3H_WSx0dK-I'},
      {name: 'Glúteos Graviton', link: 'https://www.youtube.com/embed/F2yGtpW4J4s'},
      {name: 'Glúteos Máquina', link: 'https://www.youtube.com/embed/A68gT5W_J50'},
      {name: 'Glúteos Smith', link: 'https://www.youtube.com/embed/PMbVxKqNM7I'},
      {name: 'Glúteos Cross', link: 'https://www.youtube.com/embed/vgjt9LUm6Jg'},
      {name: 'Elevação Pélvica Barra', link: 'https://www.youtube.com/embed/jqgDVIv581k'},
      {name: 'Elevação Pélvica Halter', link: 'https://www.youtube.com/embed/XNbfCoWFcFs'},
      {name: 'Elevação Pélvica Anilha', link: 'https://www.youtube.com/embed/0lPFQdMtNBU'},
      {name: 'Elevação Pélvica Smith', link: 'https://www.youtube.com/embed/0I3xQYtPCGQ'},
      {name: 'Cadeira Abdutora', link: 'https://www.youtube.com/embed/yVZ0Vs7j6EM'},
    ]
  },
  {
    isRender: false, categoryName: 'Panturrilhas',
    exerciseList: [
      {name: 'Gêmeos Em Pé Máquina', link: 'https://www.youtube.com/embed/hlQbAQB61_Y'},
      {name: 'Gêmeos Em Pé Hack', link: 'https://www.youtube.com/embed/GAn7R1U3EDw'},
      {name: 'Gêmeos Em Pé Smith', link: 'https://www.youtube.com/embed/ER72bXEam4c'},
      {name: 'Gêmeos Em Pé Livre', link: 'https://www.youtube.com/embed/VMa37XJdejk'},
      {name: 'Gêmeos Sentado Máquina', link: 'https://www.youtube.com/embed/gBIxBWBorB8'},
      {name: 'Gêmeos Sentado Smith', link: 'https://www.youtube.com/embed/iK6cVWR3-jI'},
      {name: 'Gêmeos Sentado Livre', link: 'https://www.youtube.com/embed/CiFlAqIx-lY'},
      {name: 'Gêmeos Leg Press', link: 'https://www.youtube.com/embed/omdVB4rQnoQ'},
    ]
  },
  {
    isRender: false, categoryName: 'Abdômen / Core / Lombar',
    exerciseList: [
      {name: 'Supra', link: 'https://www.youtube.com/embed/N5SL7rhM07c'},
      {name: 'Infra', link: 'https://www.youtube.com/embed/8slFJ9J31lM'},
      {name: 'Oblíquos', link: 'https://www.youtube.com/embed/k9rfQiXoM1w'},
      {name: 'Prancha', link: 'https://www.youtube.com/embed/TxadpmTHK08'},
      {name: 'Extensão Lombar', link: 'https://www.youtube.com/embed/Jto980puQ3c'},
    ]
  }
];

export default ExerciseVideoList;
